# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('eventos', '0003_auto_20170625_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Animal')),
                ('id_crecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Crecimiento')),
                ('id_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Produccion')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventoSanitario')),
            ],
        ),
    ]
