# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateField()),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=4)),
                ('codigo_RFID', models.CharField(blank=True, max_length=10, null=True)),
                ('fechamuerte', models.DateField(blank=True, null=True)),
                ('imagen_animal', models.ImageField(blank=True, default='vaca-default.jpg', null=True, upload_to='')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Raza')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoRodeo')),
            ],
        ),
        migrations.CreateModel(
            name='Toro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pajuelas', models.PositiveIntegerField(blank=True, null=True)),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Raza')),
            ],
        ),
    ]
