# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_medida', models.DateField(auto_now_add=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion de la revision a realizarse')),
                ('fecha_evento', models.DateTimeField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Animal')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tecnico')),
                ('tipo_sanitario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoSanitario')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_produccion', models.DateField(auto_now_add=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateField(null=True)),
                ('toro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Toro')),
            ],
        ),
    ]
