# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20170625_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='hora_evento',
            field=models.TimeField(null=True),
        ),
    ]
