# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_eventosanitario_hora_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosanitario',
            name='hora_evento',
            field=models.TimeField(blank=True),
        ),
    ]
