# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180413_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosanitario',
            name='hora_evento',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
